### PR TITLE
Feature/write tests

### PR DESCRIPTION
**Pull request by karlwestin**
Features 4 new integration tests:
* log in
* log in with wrong password
* add a report
* update a report

There are things that are somewhat inconvenient about the way those tests are written. I would be happy to discuss with someone how this can be done better.
* ~~the 'logout' after each test is done by clearing local storage. This makes it tied to our current implementation.~~
* ~~the example app DB's are re-setted by clearing the `.db` folder in node_modules/kazana-example. Is there a better way to do this, where we could potentially add some bootstrapping etc later on?~~

Note that it alse depends on the QA markers described here https://github.com/eHealthAfrica/kazana-example/pull/13 to be added

### CODE REVIEW

**Comment by karlwestin** [comment]
@jo would really appreciate if you had a minute to look at (first) the kazana-example PR https://github.com/eHealthAfrica/kazana-example/pull/13 and (then) this this week! Thanks!

**Comment by jo** [comment]
This depends on eHealthAfrica/kazana-example#13 right?

**Comment by karlwestin** [comment]
yeah thats right!

**Comment by jo** [comment]
LGTM

**Pull request merged**
